/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class AddJogoComanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddJogoComanada
     */
    String cpf;
    GerenciaComanda fonte;
    Connection con;
    public AddJogoComanda(GerenciaComanda f,String cpf) {
        initComponents();
        fonte = f;
        this.cpf = cpf;
        try {
            con = ConnectionFactory.createConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodJogo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spinQtdJogo = new javax.swing.JSpinner();
        btnCancelaAddJogo = new javax.swing.JButton();
        btnAddJogo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Adicionar Jogo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Código do Jogo:");

        jLabel2.setText("Quantidade:");

        spinQtdJogo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnCancelaAddJogo.setText("Cancelar");
        btnCancelaAddJogo.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaAddJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaAddJogoActionPerformed(evt);
            }
        });

        btnAddJogo.setText("Adicionar");
        btnAddJogo.setPreferredSize(new java.awt.Dimension(100, 23));
        btnAddJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelaAddJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinQtdJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 182, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodJogo)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinQtdJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaAddJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBounds(0, 0, 360, 150);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaAddJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaAddJogoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaAddJogoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AddJogoComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        fonte.btnAddJogo.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnAddJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogoActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO comanda_compra_jogos(cpf_cliente,codigo,quantidade) "
                + "VALUES ("+cpf+","+txtCodJogo.getText()+","+spinQtdJogo.getValue()+")";
        try {
            PreparedStatement stm = con.prepareStatement(sql);
            stm.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(fonte.jp, "Não foi possível adicionar jogo!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(fonte.jp, "Jogo adicionado com sucesso!","Cadastro",JOptionPane.INFORMATION_MESSAGE);
        txtCodJogo.setText("");
        spinQtdJogo.setValue(1);
        
        GerenciaComanda gerenciaComanda = new GerenciaComanda(cpf,fonte.jp);
        fonte.jp.jDesktopPane1.add(gerenciaComanda);
        Dimension d = fonte.jp.jDesktopPane1.getSize();
        gerenciaComanda.setLocation((d.width - gerenciaComanda.getSize().width) / 2, (d.height - gerenciaComanda.getSize().height) / 2);
        gerenciaComanda.setVisible(true);
        fonte.dispose();
        this.moveToFront();
        try {
            this.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AddItemComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        fonte = gerenciaComanda;
    }//GEN-LAST:event_btnAddJogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJogo;
    private javax.swing.JButton btnCancelaAddJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinQtdJogo;
    private javax.swing.JTextField txtCodJogo;
    // End of variables declaration//GEN-END:variables
}
