/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;

/**
 *
 * @author d-den
 */
public class BuscaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form buscaCliente
     */
    JanelaPrincipal jp;
    public BuscaCliente(JanelaPrincipal j) {
        initComponents();
        jp = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbBuscaCPF = new javax.swing.JCheckBox();
        cbBuscaNome = new javax.swing.JCheckBox();
        cbBuscaRG = new javax.swing.JCheckBox();
        cbBuscaTel = new javax.swing.JCheckBox();
        cbBuscaCidade = new javax.swing.JCheckBox();
        cbBuscaCEP = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        cbExibeNome = new javax.swing.JCheckBox();
        cbExibeRua = new javax.swing.JCheckBox();
        cbExibeBairro = new javax.swing.JCheckBox();
        cbExibeCidade = new javax.swing.JCheckBox();
        cbExibeCEP = new javax.swing.JCheckBox();
        cbExibeRG = new javax.swing.JCheckBox();
        cbExibeTel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscaNome = new javax.swing.JTextField();
        txtBuscaTel = new javax.swing.JTextField();
        txtBuscaCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBuscaCEP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCancelaBuscaCli = new javax.swing.JButton();
        btnBuscaCli = new javax.swing.JButton();
        txtBuscaCPF = new javax.swing.JFormattedTextField();
        txtBuscaRG = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar por"));

        cbBuscaCPF.setSelected(true);
        cbBuscaCPF.setText("CPF");
        cbBuscaCPF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCPFStateChanged(evt);
            }
        });

        cbBuscaNome.setText("Nome");
        cbBuscaNome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaNomeStateChanged(evt);
            }
        });

        cbBuscaRG.setText("RG");
        cbBuscaRG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaRGStateChanged(evt);
            }
        });

        cbBuscaTel.setText("Telefone");
        cbBuscaTel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaTelStateChanged(evt);
            }
        });

        cbBuscaCidade.setText("Cidade");
        cbBuscaCidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCidadeStateChanged(evt);
            }
        });

        cbBuscaCEP.setText("CEP");
        cbBuscaCEP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCEPStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscaCPF)
                    .addComponent(cbBuscaNome))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscaCidade)
                    .addComponent(cbBuscaCEP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscaTel)
                    .addComponent(cbBuscaRG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscaCPF)
                    .addComponent(cbBuscaRG)
                    .addComponent(cbBuscaCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscaNome)
                    .addComponent(cbBuscaTel)
                    .addComponent(cbBuscaCEP)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Exibir"));

        jCheckBox7.setSelected(true);
        jCheckBox7.setText("CPF");
        jCheckBox7.setEnabled(false);

        cbExibeNome.setText("Nome");

        cbExibeRua.setText("Rua");

        cbExibeBairro.setText("Bairro");

        cbExibeCidade.setText("Cidade");

        cbExibeCEP.setText("CEP");

        cbExibeRG.setText("RG");

        cbExibeTel.setText("Telefone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7)
                    .addComponent(cbExibeNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeRua)
                    .addComponent(cbExibeBairro))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeCidade)
                    .addComponent(cbExibeCEP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeTel)
                    .addComponent(cbExibeRG)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(cbExibeRua)
                    .addComponent(cbExibeCidade)
                    .addComponent(cbExibeRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibeNome)
                    .addComponent(cbExibeBairro)
                    .addComponent(cbExibeCEP)
                    .addComponent(cbExibeTel)))
        );

        jLabel1.setText("CPF:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Cidade:");

        txtBuscaNome.setEnabled(false);

        txtBuscaTel.setEnabled(false);

        txtBuscaCidade.setEnabled(false);

        jLabel5.setText("CEP:");

        txtBuscaCEP.setEnabled(false);

        jLabel6.setText("RG:");

        btnCancelaBuscaCli.setText("Cancelar");
        btnCancelaBuscaCli.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaBuscaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaBuscaCliActionPerformed(evt);
            }
        });

        btnBuscaCli.setText("Buscar");
        btnBuscaCli.setPreferredSize(new java.awt.Dimension(100, 23));
        btnBuscaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCliActionPerformed(evt);
            }
        });

        try {
            txtBuscaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtBuscaRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaRG.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscaRG, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                                    .addComponent(txtBuscaCidade)
                                    .addComponent(txtBuscaNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscaTel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscaCEP)))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelaBuscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscaTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscaCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaBuscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setBounds(0, 0, 620, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaBuscaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaBuscaCliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaBuscaCliActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        jp.menuBuscaCli.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void cbBuscaCPFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCPFStateChanged
        // TODO add your handling code here:
        if(cbBuscaCPF.isSelected())
            txtBuscaCPF.setEnabled(true);
        else
            txtBuscaCPF.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCPFStateChanged

    private void cbBuscaCidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCidadeStateChanged
        // TODO add your handling code here:
        if(cbBuscaCidade.isSelected())
            txtBuscaCidade.setEnabled(true);
        else
            txtBuscaCidade.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCidadeStateChanged

    private void cbBuscaRGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaRGStateChanged
        // TODO add your handling code here:
        if(cbBuscaRG.isSelected())
            txtBuscaRG.setEnabled(true);
        else
            txtBuscaRG.setEnabled(false);
    }//GEN-LAST:event_cbBuscaRGStateChanged

    private void cbBuscaNomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaNomeStateChanged
        // TODO add your handling code here:
        if(cbBuscaNome.isSelected())
            txtBuscaNome.setEnabled(true);
        else
            txtBuscaNome.setEnabled(false);
    }//GEN-LAST:event_cbBuscaNomeStateChanged

    private void cbBuscaCEPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCEPStateChanged
        // TODO add your handling code here:
        if(cbBuscaCEP.isSelected())
            txtBuscaCEP.setEnabled(true);
        else
            txtBuscaCEP.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCEPStateChanged

    private void cbBuscaTelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaTelStateChanged
        // TODO add your handling code here:
        if(cbBuscaTel.isSelected())
            txtBuscaTel.setEnabled(true);
        else
            txtBuscaTel.setEnabled(false);
    }//GEN-LAST:event_cbBuscaTelStateChanged

    private void btnBuscaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCliActionPerformed
        // TODO add your handling code here:
        btnBuscaCli.setEnabled(false);
        ResultadoBuscaCli resBuscaCli = new ResultadoBuscaCli(this);
        jp.jDesktopPane1.add(resBuscaCli);
        Dimension d = jp.jDesktopPane1.getSize();
        resBuscaCli.setLocation((d.width - resBuscaCli.getSize().width) / 2, (d.height - resBuscaCli.getSize().height) / 2);
        resBuscaCli.setVisible(true);
    }//GEN-LAST:event_btnBuscaCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscaCli;
    private javax.swing.JButton btnCancelaBuscaCli;
    private javax.swing.JCheckBox cbBuscaCEP;
    private javax.swing.JCheckBox cbBuscaCPF;
    private javax.swing.JCheckBox cbBuscaCidade;
    private javax.swing.JCheckBox cbBuscaNome;
    private javax.swing.JCheckBox cbBuscaRG;
    private javax.swing.JCheckBox cbBuscaTel;
    private javax.swing.JCheckBox cbExibeBairro;
    private javax.swing.JCheckBox cbExibeCEP;
    private javax.swing.JCheckBox cbExibeCidade;
    private javax.swing.JCheckBox cbExibeNome;
    private javax.swing.JCheckBox cbExibeRG;
    private javax.swing.JCheckBox cbExibeRua;
    private javax.swing.JCheckBox cbExibeTel;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBuscaCEP;
    private javax.swing.JFormattedTextField txtBuscaCPF;
    private javax.swing.JTextField txtBuscaCidade;
    private javax.swing.JTextField txtBuscaNome;
    private javax.swing.JFormattedTextField txtBuscaRG;
    private javax.swing.JTextField txtBuscaTel;
    // End of variables declaration//GEN-END:variables
}
