/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class BuscaJogo extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaJogo
     */
    JanelaPrincipal jp;
    Connection con;
    public BuscaJogo(JanelaPrincipal j) {
        initComponents();
        jp = j;
        try{
            con = ConnectionFactory.createConnection();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            
            return;
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
           
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbBuscaCodigo = new javax.swing.JCheckBox();
        cbBuscaNome = new javax.swing.JCheckBox();
        cbBuscaDesc = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cbExibeCodigo = new javax.swing.JCheckBox();
        cbExibeNome = new javax.swing.JCheckBox();
        cbExibeDesc = new javax.swing.JCheckBox();
        cbExibePreco = new javax.swing.JCheckBox();
        cbExibeEstoque = new javax.swing.JCheckBox();
        cbExibeLocacao = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cbFiltraEstoque = new javax.swing.JCheckBox();
        cbFiltraLoc = new javax.swing.JCheckBox();
        cbbEstoque = new javax.swing.JComboBox<>();
        cbbLoc = new javax.swing.JComboBox<>();
        cbFiltraPreco = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtMinPreco = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaxPreco = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscaDesc = new javax.swing.JTextField();
        txtBuscaNome = new javax.swing.JTextField();
        txtBuscaCod = new javax.swing.JTextField();
        btnCancelaBuscaJogo = new javax.swing.JButton();
        btnBuscaJogo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Jogo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busca por"));

        cbBuscaCodigo.setSelected(true);
        cbBuscaCodigo.setText("Código");
        cbBuscaCodigo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCodigoStateChanged(evt);
            }
        });

        cbBuscaNome.setText("Nome");
        cbBuscaNome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaNomeStateChanged(evt);
            }
        });

        cbBuscaDesc.setText("Descrição");
        cbBuscaDesc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaDescStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbBuscaCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(cbBuscaDesc))
                    .addComponent(cbBuscaNome)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscaCodigo)
                    .addComponent(cbBuscaDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBuscaNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Exibir"));

        cbExibeCodigo.setSelected(true);
        cbExibeCodigo.setText("Código");
        cbExibeCodigo.setEnabled(false);

        cbExibeNome.setText("Nome");

        cbExibeDesc.setText("Descrição");

        cbExibePreco.setText("Preço");

        cbExibeEstoque.setText("Em estoque");

        cbExibeLocacao.setText("Locação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeCodigo)
                    .addComponent(cbExibeNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeDesc)
                    .addComponent(cbExibePreco))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibeLocacao)
                    .addComponent(cbExibeEstoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibeCodigo)
                    .addComponent(cbExibeDesc)
                    .addComponent(cbExibeEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibeNome)
                    .addComponent(cbExibePreco)
                    .addComponent(cbExibeLocacao))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filtrar por"));

        cbFiltraEstoque.setText("Em estoque:");
        cbFiltraEstoque.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFiltraEstoqueStateChanged(evt);
            }
        });

        cbFiltraLoc.setText("Para locação:");
        cbFiltraLoc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFiltraLocStateChanged(evt);
            }
        });

        cbbEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cbbEstoque.setEnabled(false);

        cbbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        cbbLoc.setEnabled(false);

        cbFiltraPreco.setText("Preço:");
        cbFiltraPreco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFiltraPrecoStateChanged(evt);
            }
        });

        jLabel1.setText("Mínimo:");

        txtMinPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtMinPreco.setEnabled(false);

        jLabel2.setText("Máximo:");

        txtMaxPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtMaxPreco.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbFiltraLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFiltraEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbbEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbFiltraPreco))
                    .addComponent(cbbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinPreco)
                    .addComponent(txtMaxPreco))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltraEstoque)
                    .addComponent(cbbEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltraPreco)
                    .addComponent(jLabel1)
                    .addComponent(txtMinPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltraLoc)
                    .addComponent(cbbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setText("Código:");

        jLabel4.setText("Nome:");

        jLabel5.setText("Descrição:");

        txtBuscaDesc.setEnabled(false);

        txtBuscaNome.setEnabled(false);

        btnCancelaBuscaJogo.setText("Cancelar");
        btnCancelaBuscaJogo.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaBuscaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaBuscaJogoActionPerformed(evt);
            }
        });

        btnBuscaJogo.setText("Buscar");
        btnBuscaJogo.setPreferredSize(new java.awt.Dimension(100, 23));
        btnBuscaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscaDesc)
                            .addComponent(txtBuscaNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelaBuscaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnBuscaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaBuscaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setBounds(0, 0, 500, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        jp.menuBuscaJogo.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnCancelaBuscaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaBuscaJogoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaBuscaJogoActionPerformed

    private void cbBuscaCodigoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCodigoStateChanged
        // TODO add your handling code here:
        if(cbBuscaCodigo.isSelected())
            txtBuscaCod.setEnabled(true);
        else
            txtBuscaCod.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCodigoStateChanged

    private void cbBuscaDescStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaDescStateChanged
        // TODO add your handling code here:
        if(cbBuscaDesc.isSelected())
            txtBuscaDesc.setEnabled(true);
        else
            txtBuscaDesc.setEnabled(false);
    }//GEN-LAST:event_cbBuscaDescStateChanged

    private void cbBuscaNomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaNomeStateChanged
        // TODO add your handling code here:
        if(cbBuscaNome.isSelected())
            txtBuscaNome.setEnabled(true);
        else
            txtBuscaNome.setEnabled(false);
    }//GEN-LAST:event_cbBuscaNomeStateChanged

    private void cbFiltraEstoqueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFiltraEstoqueStateChanged
        // TODO add your handling code here:
        if(cbFiltraEstoque.isSelected())
            cbbEstoque.setEnabled(true);
        else
            cbbEstoque.setEnabled(false);
    }//GEN-LAST:event_cbFiltraEstoqueStateChanged

    private void cbFiltraLocStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFiltraLocStateChanged
        // TODO add your handling code here:
        if(cbFiltraLoc.isSelected())
            cbbLoc.setEnabled(true);
        else
            cbbLoc.setEnabled(false);
    }//GEN-LAST:event_cbFiltraLocStateChanged

    private void cbFiltraPrecoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFiltraPrecoStateChanged
        // TODO add your handling code here:
        if(cbFiltraPreco.isSelected()){
            txtMinPreco.setEnabled(true);
            txtMaxPreco.setEnabled(true);
        }else{
            txtMinPreco.setEnabled(false);
            txtMaxPreco.setEnabled(false);
        }
    }//GEN-LAST:event_cbFiltraPrecoStateChanged

    private void btnBuscaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaJogoActionPerformed
        // TODO add your handling code here:
        
        ResultSet rs = null;
        String colunas = "codigo_jogo,";
        if(cbExibeNome.isSelected())
            colunas = colunas + "nome_jogo,";
        if(cbExibeDesc.isSelected())
            colunas = colunas + "descricao_jogo,";
        if(cbExibeEstoque.isSelected())
            colunas = colunas + "em_estoque,";
        if(cbExibeLocacao.isSelected())
            colunas = colunas + "locacao,";
        if(cbExibePreco.isSelected())
            colunas = colunas + "preco_jogo,";
        colunas = colunas.substring(0, colunas.length()-1);
        String sql = "SELECT " + colunas + " FROM jogo ";
        String busca = "";
        if(cbBuscaCodigo.isSelected() || cbBuscaDesc.isSelected() || cbBuscaNome.isSelected() || cbFiltraEstoque.isSelected() || cbFiltraPreco.isSelected() || cbFiltraLoc.isSelected()){
            sql = sql + "WHERE";
            if(cbBuscaCodigo.isSelected()){
                if(txtBuscaCod.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaJogo.setEnabled(true);
                    return;
                }
                busca = busca + " codigo_jogo = " + txtBuscaCod.getText() + " and";
            }
            if(cbBuscaDesc.isSelected()){
                if(txtBuscaDesc.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaJogo.setEnabled(true);
                    return;
                }
                busca = busca + " descricao_jogo like '%" + txtBuscaDesc.getText() + "%' and";
            }
            if(cbBuscaNome.isSelected()){
                if(txtBuscaNome.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaJogo.setEnabled(true);
                    return;
                }
                busca = busca + " nome_jogo like '%" + txtBuscaNome.getText() + "%' and";
            }
            if(cbFiltraEstoque.isSelected()){
                int op = cbbEstoque.getSelectedIndex();
                if(op == 0)
                    busca = busca + " em_estoque = true and";
                else
                    busca = busca + " em_estoque = false and";
            }
            if(cbFiltraLoc.isSelected()){
                int op = cbbLoc.getSelectedIndex();
                if(op == 0)
                    busca = busca + " locacao = true and";
                else
                    busca = busca + " locacao = false and";
            }
            if(cbFiltraPreco.isSelected()){
                if(txtMinPreco.getText().isEmpty() || txtMaxPreco.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaJogo.setEnabled(true);
                    return;
                }
                busca = busca + " preco_jogo BETWEEN "+txtMinPreco.getText().replace(',', '.')+" AND "+txtMaxPreco.getText().replace(',', '.')+" and";
            }
            busca = busca.substring(0, busca.length()-3); // remove ultimo and
            sql = sql + busca;
        }
        
        try{
            PreparedStatement stm = con.prepareStatement(sql);
            rs = stm.executeQuery();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(jp, "Não foi possível realizar busca no Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            btnBuscaJogo.setEnabled(true);
            return;
        }
        
        ResultadoBuscaJogo resBuscaJogo = new ResultadoBuscaJogo(this,rs);
        jp.jDesktopPane1.add(resBuscaJogo);
        Dimension d = jp.jDesktopPane1.getSize();
        resBuscaJogo.setLocation((d.width - resBuscaJogo.getSize().width) / 2, (d.height - resBuscaJogo.getSize().height) / 2);
        resBuscaJogo.setVisible(true);
        btnBuscaJogo.setEnabled(false);
    }//GEN-LAST:event_btnBuscaJogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscaJogo;
    private javax.swing.JButton btnCancelaBuscaJogo;
    private javax.swing.JCheckBox cbBuscaCodigo;
    private javax.swing.JCheckBox cbBuscaDesc;
    private javax.swing.JCheckBox cbBuscaNome;
    private javax.swing.JCheckBox cbExibeCodigo;
    private javax.swing.JCheckBox cbExibeDesc;
    private javax.swing.JCheckBox cbExibeEstoque;
    private javax.swing.JCheckBox cbExibeLocacao;
    private javax.swing.JCheckBox cbExibeNome;
    private javax.swing.JCheckBox cbExibePreco;
    private javax.swing.JCheckBox cbFiltraEstoque;
    private javax.swing.JCheckBox cbFiltraLoc;
    private javax.swing.JCheckBox cbFiltraPreco;
    private javax.swing.JComboBox<String> cbbEstoque;
    private javax.swing.JComboBox<String> cbbLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtBuscaCod;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextField txtBuscaNome;
    private javax.swing.JFormattedTextField txtMaxPreco;
    private javax.swing.JFormattedTextField txtMinPreco;
    // End of variables declaration//GEN-END:variables
}
