/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class BuscaComanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaComanda
     */
    JanelaPrincipal jp;
    Connection con;
    public BuscaComanda(JanelaPrincipal j) {
        initComponents();
        jp = j;
        try{
            con = ConnectionFactory.createConnection();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            
            return;
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
           
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbBuscaCPFCli = new javax.swing.JCheckBox();
        cbBuscaCPFFunc = new javax.swing.JCheckBox();
        cbBuscaNomeFunc = new javax.swing.JCheckBox();
        cbBuscaNomeCli = new javax.swing.JCheckBox();
        cbBuscaNomeJogo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        cbExibirCPFFunc = new javax.swing.JCheckBox();
        cbExibirCodJogo = new javax.swing.JCheckBox();
        cbExibirNomeJogo = new javax.swing.JCheckBox();
        cbExibirVal = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cbFiltrarVal = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtMinVal = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaxVal = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscaNomeFunc = new javax.swing.JTextField();
        txtBuscaNomeJogo = new javax.swing.JTextField();
        txtBuscaNomeCli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBuscaCPFCli = new javax.swing.JFormattedTextField();
        txtBuscaCPFFunc = new javax.swing.JFormattedTextField();
        btnCancelaBuscaComanda = new javax.swing.JButton();
        btnBuscaComanda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Comanda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar por"));

        cbBuscaCPFCli.setSelected(true);
        cbBuscaCPFCli.setText("CPF do Cliente");
        cbBuscaCPFCli.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCPFCliStateChanged(evt);
            }
        });

        cbBuscaCPFFunc.setText("CPF do Funcionário");
        cbBuscaCPFFunc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaCPFFuncStateChanged(evt);
            }
        });

        cbBuscaNomeFunc.setText("Nome de Funcionário");
        cbBuscaNomeFunc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaNomeFuncStateChanged(evt);
            }
        });

        cbBuscaNomeCli.setText("Nome do Cliente");
        cbBuscaNomeCli.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaNomeCliStateChanged(evt);
            }
        });

        cbBuscaNomeJogo.setText("Nome do Jogo Alugado");
        cbBuscaNomeJogo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscaNomeJogoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBuscaCPFFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(cbBuscaCPFCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBuscaNomeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBuscaNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbBuscaNomeJogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscaCPFCli)
                    .addComponent(cbBuscaNomeCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscaCPFFunc)
                    .addComponent(cbBuscaNomeFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBuscaNomeJogo)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Exibir"));

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("CPF do Cliente");
        jCheckBox6.setEnabled(false);

        cbExibirCPFFunc.setText("CPF do Funcionário");

        cbExibirCodJogo.setText("Código do Jogo Alugado");

        cbExibirNomeJogo.setText("Nome do Jogo Alugado");

        cbExibirVal.setText("Valor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbExibirCodJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbExibirCPFFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibirNomeJogo)
                    .addComponent(cbExibirVal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(cbExibirNomeJogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibirCPFFunc)
                    .addComponent(cbExibirVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbExibirCodJogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filtrar por"));

        cbFiltrarVal.setText("Valor");
        cbFiltrarVal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFiltrarValStateChanged(evt);
            }
        });

        jLabel1.setText("Mínimo:");

        txtMinVal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtMinVal.setEnabled(false);

        jLabel2.setText("Máximo:");

        txtMaxVal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtMaxVal.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFiltrarVal)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinVal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaxVal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbFiltrarVal)
                .addComponent(jLabel1)
                .addComponent(txtMinVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(txtMaxVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("CPF do Cliente:");

        jLabel4.setText("Nome do Cliente:");

        jLabel5.setText("Nome do Funcionário:");

        jLabel6.setText("Nome do Jogo:");

        txtBuscaNomeFunc.setEnabled(false);

        txtBuscaNomeJogo.setEnabled(false);

        txtBuscaNomeCli.setEnabled(false);

        jLabel7.setText("CPF do Funcionário:");

        try {
            txtBuscaCPFCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtBuscaCPFFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaCPFFunc.setEnabled(false);

        btnCancelaBuscaComanda.setText("Cancelar");
        btnCancelaBuscaComanda.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaBuscaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaBuscaComandaActionPerformed(evt);
            }
        });

        btnBuscaComanda.setText("Buscar");
        btnBuscaComanda.setPreferredSize(new java.awt.Dimension(100, 23));
        btnBuscaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscaCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaCPFFunc))
                            .addComponent(txtBuscaNomeFunc)
                            .addComponent(txtBuscaNomeJogo)
                            .addComponent(txtBuscaNomeCli)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelaBuscaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(btnBuscaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscaCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscaNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscaNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscaNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaBuscaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setBounds(0, 0, 700, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        jp.menuBuscaComanda.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnCancelaBuscaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaBuscaComandaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaBuscaComandaActionPerformed

    private void btnBuscaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaComandaActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        String colunas = " cpf_cliente,";
        if(cbExibirCPFFunc.isSelected())
            colunas = colunas + "cpf_funcionario,";
        if(cbExibirCPFFunc.isSelected())
            colunas = colunas + "cpf_funcionario,";
        
        btnBuscaComanda.setEnabled(false);
        ResultadoBuscaComanda resBuscaComanda = new ResultadoBuscaComanda(this);
        jp.jDesktopPane1.add(resBuscaComanda);
        Dimension d = jp.jDesktopPane1.getSize();
        resBuscaComanda.setLocation((d.width - resBuscaComanda.getSize().width) / 2, (d.height - resBuscaComanda.getSize().height) / 2);
        resBuscaComanda.setVisible(true);
    }//GEN-LAST:event_btnBuscaComandaActionPerformed

    private void cbBuscaCPFCliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCPFCliStateChanged
        // TODO add your handling code here:
        if(cbBuscaCPFCli.isSelected())
            txtBuscaCPFCli.setEnabled(true);
        else
            txtBuscaCPFCli.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCPFCliStateChanged

    private void cbBuscaCPFFuncStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaCPFFuncStateChanged
        // TODO add your handling code here:
        if(cbBuscaCPFFunc.isSelected())
            txtBuscaCPFFunc.setEnabled(true);
        else
            txtBuscaCPFFunc.setEnabled(false);
    }//GEN-LAST:event_cbBuscaCPFFuncStateChanged

    private void cbBuscaNomeJogoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaNomeJogoStateChanged
        // TODO add your handling code here:
        if(cbBuscaNomeJogo.isSelected())
            txtBuscaNomeJogo.setEnabled(true);
        else
            txtBuscaNomeJogo.setEnabled(false);
    }//GEN-LAST:event_cbBuscaNomeJogoStateChanged

    private void cbBuscaNomeCliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaNomeCliStateChanged
        // TODO add your handling code here:
        if(cbBuscaNomeCli.isSelected())
            txtBuscaNomeCli.setEnabled(true);
        else
            txtBuscaNomeCli.setEnabled(false);
    }//GEN-LAST:event_cbBuscaNomeCliStateChanged

    private void cbBuscaNomeFuncStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscaNomeFuncStateChanged
        // TODO add your handling code here:
        if(cbBuscaNomeFunc.isSelected())
            txtBuscaNomeFunc.setEnabled(true);
        else
            txtBuscaNomeFunc.setEnabled(false);
    }//GEN-LAST:event_cbBuscaNomeFuncStateChanged

    private void cbFiltrarValStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFiltrarValStateChanged
        // TODO add your handling code here:
        if(cbFiltrarVal.isSelected()){
            txtMinVal.setEnabled(true);
            txtMaxVal.setEnabled(true);
        }else{
            txtMinVal.setEnabled(false);
            txtMaxVal.setEnabled(false);
        }
    }//GEN-LAST:event_cbFiltrarValStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscaComanda;
    private javax.swing.JButton btnCancelaBuscaComanda;
    private javax.swing.JCheckBox cbBuscaCPFCli;
    private javax.swing.JCheckBox cbBuscaCPFFunc;
    private javax.swing.JCheckBox cbBuscaNomeCli;
    private javax.swing.JCheckBox cbBuscaNomeFunc;
    private javax.swing.JCheckBox cbBuscaNomeJogo;
    private javax.swing.JCheckBox cbExibirCPFFunc;
    private javax.swing.JCheckBox cbExibirCodJogo;
    private javax.swing.JCheckBox cbExibirNomeJogo;
    private javax.swing.JCheckBox cbExibirVal;
    private javax.swing.JCheckBox cbFiltrarVal;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField txtBuscaCPFCli;
    private javax.swing.JFormattedTextField txtBuscaCPFFunc;
    private javax.swing.JTextField txtBuscaNomeCli;
    private javax.swing.JTextField txtBuscaNomeFunc;
    private javax.swing.JTextField txtBuscaNomeJogo;
    private javax.swing.JFormattedTextField txtMaxVal;
    private javax.swing.JFormattedTextField txtMinVal;
    // End of variables declaration//GEN-END:variables
}
