/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class BuscaFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaFuncionario
     */
    public JanelaPrincipal jp;
    Connection con;
    public BuscaFuncionario(JanelaPrincipal j) {
        initComponents();
        jp = j;
        try{
            con = ConnectionFactory.createConnection();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            
            return;
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(jp, "Não foi possível conectar ao Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
           
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbBuscarCPF = new javax.swing.JCheckBox();
        cbBuscarNome = new javax.swing.JCheckBox();
        cbBuscarCTPS = new javax.swing.JCheckBox();
        cbBuscarCidade = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cbExibirCPF = new javax.swing.JCheckBox();
        cbExibirNome = new javax.swing.JCheckBox();
        cbExibirRua = new javax.swing.JCheckBox();
        cbExibirBairro = new javax.swing.JCheckBox();
        cbExibirCidade = new javax.swing.JCheckBox();
        cbExibirCEP = new javax.swing.JCheckBox();
        cbExibirSalario = new javax.swing.JCheckBox();
        cbExibirCTPS = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cbFiltrarSalario = new javax.swing.JCheckBox();
        txtSalMax = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSalMin = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscaCidade = new javax.swing.JTextField();
        txtBuscaNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBuscaCPF = new javax.swing.JFormattedTextField();
        txtBuscaCTPS = new javax.swing.JFormattedTextField();
        btnCancelaBusca = new javax.swing.JButton();
        btnBuscaFunc = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Funcionário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar por"));

        cbBuscarCPF.setSelected(true);
        cbBuscarCPF.setText("CPF");
        cbBuscarCPF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscarCPFStateChanged(evt);
            }
        });

        cbBuscarNome.setText("Nome");
        cbBuscarNome.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscarNomeStateChanged(evt);
            }
        });

        cbBuscarCTPS.setText("CTPS");
        cbBuscarCTPS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscarCTPSStateChanged(evt);
            }
        });

        cbBuscarCidade.setText("Cidade");
        cbBuscarCidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbBuscarCidadeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscarNome)
                    .addComponent(cbBuscarCPF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscarCTPS)
                    .addComponent(cbBuscarCidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscarCPF)
                    .addComponent(cbBuscarCTPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuscarNome)
                    .addComponent(cbBuscarCidade))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Exibir"));

        cbExibirCPF.setSelected(true);
        cbExibirCPF.setText("CPF");
        cbExibirCPF.setEnabled(false);

        cbExibirNome.setText("Nome");

        cbExibirRua.setText("Rua");

        cbExibirBairro.setText("Bairro");

        cbExibirCidade.setText("Cidade");

        cbExibirCEP.setText("Número");

        cbExibirSalario.setText("Salário");

        cbExibirCTPS.setText("CTPS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibirCPF)
                    .addComponent(cbExibirNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibirRua)
                    .addComponent(cbExibirBairro))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibirCEP)
                    .addComponent(cbExibirCidade))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbExibirCTPS)
                    .addComponent(cbExibirSalario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibirCPF)
                    .addComponent(cbExibirRua)
                    .addComponent(cbExibirCidade)
                    .addComponent(cbExibirSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbExibirNome)
                    .addComponent(cbExibirBairro)
                    .addComponent(cbExibirCEP)
                    .addComponent(cbExibirCTPS))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filtrar por"));

        cbFiltrarSalario.setText("Salário");
        cbFiltrarSalario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbFiltrarSalarioStateChanged(evt);
            }
        });

        txtSalMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtSalMax.setEnabled(false);

        jLabel1.setText("Máximo:");

        txtSalMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        txtSalMin.setEnabled(false);

        jLabel2.setText("Mínimo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFiltrarSalario)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltrarSalario)
                    .addComponent(txtSalMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("CPF:");

        jLabel4.setText("Nome:");

        jLabel5.setText("Cidade:");

        txtBuscaCidade.setEnabled(false);

        txtBuscaNome.setEnabled(false);

        jLabel6.setText("CTPS:");

        try {
            txtBuscaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtBuscaCTPS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaCTPS.setEnabled(false);

        btnCancelaBusca.setText("Cancelar");
        btnCancelaBusca.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaBuscaActionPerformed(evt);
            }
        });

        btnBuscaFunc.setText("Buscar");
        btnBuscaFunc.setPreferredSize(new java.awt.Dimension(100, 23));
        btnBuscaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaCTPS))
                            .addComponent(txtBuscaCidade)
                            .addComponent(txtBuscaNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(btnBuscaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setBounds(0, 0, 520, 345);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(BuscaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        jp.menuBuscaFunc.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnCancelaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaBuscaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaBuscaActionPerformed

    private void cbBuscarCPFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscarCPFStateChanged
        // TODO add your handling code here:
        if(cbBuscarCPF.isSelected())
            txtBuscaCPF.setEnabled(true);
        else
            txtBuscaCPF.setEnabled(false);
    }//GEN-LAST:event_cbBuscarCPFStateChanged

    private void cbBuscarCTPSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscarCTPSStateChanged
        // TODO add your handling code here:
        if(cbBuscarCTPS.isSelected())
            txtBuscaCTPS.setEnabled(true);
        else
            txtBuscaCTPS.setEnabled(false);
    }//GEN-LAST:event_cbBuscarCTPSStateChanged

    private void cbBuscarNomeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscarNomeStateChanged
        // TODO add your handling code here:
        if(cbBuscarNome.isSelected())
            txtBuscaNome.setEnabled(true);
        else
            txtBuscaNome.setEnabled(false);
    }//GEN-LAST:event_cbBuscarNomeStateChanged

    private void cbBuscarCidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbBuscarCidadeStateChanged
        // TODO add your handling code here:
        if(cbBuscarCidade.isSelected())
            txtBuscaCidade.setEnabled(true);
        else
            txtBuscaCidade.setEnabled(false);
    }//GEN-LAST:event_cbBuscarCidadeStateChanged

    private void cbFiltrarSalarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFiltrarSalarioStateChanged
        // TODO add your handling code here:
        if(cbFiltrarSalario.isSelected()){
            txtSalMin.setEnabled(true);
            txtSalMax.setEnabled(true);
        }else{
            txtSalMin.setEnabled(false);
            txtSalMax.setEnabled(false);
        }
    }//GEN-LAST:event_cbFiltrarSalarioStateChanged

    private void btnBuscaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaFuncActionPerformed
        // TODO add your handling code here:
        
        ResultSet rs = null;
        String colunas = "cpf as CPF,";
        if(cbExibirCTPS.isSelected())
            colunas = colunas + "ctps as CTPS,";
        if(cbExibirNome.isSelected())
            colunas = colunas + "nome as Nome,";
        if(cbExibirRua.isSelected())
            colunas = colunas + "rua as Rua,";
        if(cbExibirBairro.isSelected())
            colunas = colunas + "bairro as Bairro,";
        if(cbExibirCidade.isSelected())
            colunas = colunas + "cidade as Cidade,";
        if(cbExibirCEP.isSelected())
            colunas = colunas + "num as Número,";
        if(cbExibirSalario.isSelected())
            colunas = colunas + "salario as Salário,";
        colunas = colunas.substring(0, colunas.length()-1); // elimina a ultima virgula
        String sql = "SELECT " + colunas + " FROM pessoaFunc ";
        String busca = "";
        if(cbBuscarCPF.isSelected() || cbBuscarCTPS.isSelected() || cbBuscarNome.isSelected() || cbBuscarCidade.isSelected() || cbFiltrarSalario.isSelected()){
            sql = sql + "WHERE";
            if(cbBuscarCPF.isSelected()){
                if(txtBuscaCPF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaFunc.setEnabled(true);
                    return;
                }
                busca = busca + " cpf = " + txtBuscaCPF.getText() + " and";
            }
            if(cbBuscarCTPS.isSelected()){
                if(txtBuscaCTPS.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaFunc.setEnabled(true);
                    return;
                }
                busca = busca + " ctps = " + txtBuscaCTPS.getText() + " and";
            }
            if(cbBuscarNome.isSelected()){
                if(txtBuscaNome.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaFunc.setEnabled(true);
                    return;
                }
                busca = busca + " nome like '%" + txtBuscaNome.getText() + "%' and";
            }
            if(cbBuscarCidade.isSelected()){
                if(txtBuscaCidade.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaFunc.setEnabled(true);
                    return;
                }
                busca = busca + " cidade like '%" + txtBuscaCidade.getText() + "%' and";
            }
            if(cbFiltrarSalario.isSelected()){
                if(txtSalMin.getText().isEmpty() || txtSalMax.getText().isEmpty()){
                    JOptionPane.showMessageDialog(jp, "Preencha todos os campos!","Atenção",JOptionPane.WARNING_MESSAGE);
                    btnBuscaFunc.setEnabled(true);
                    return;
                }
                busca = busca + " salario BETWEEN "+txtSalMin.getText().replace(',', '.')+" AND "+txtSalMax.getText().replace(',', '.')+" and";
            }
            busca = busca.substring(0, busca.length()-3); // remove ultimo and
            sql = sql + busca;
        }
        
        try{
            PreparedStatement stm = con.prepareStatement(sql);
            rs = stm.executeQuery();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(jp, "Não foi possível realizar busca no Banco de Dados!\n+"+ex.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            btnBuscaFunc.setEnabled(true);
            return;
        }
        
        ResultadoBuscaFunc resBuscaFunc = new ResultadoBuscaFunc(this,rs);
        jp.jDesktopPane1.add(resBuscaFunc);
        Dimension d = jp.jDesktopPane1.getSize();
        resBuscaFunc.setLocation((d.width - resBuscaFunc.getSize().width) / 2, (d.height - resBuscaFunc.getSize().height) / 2);
        resBuscaFunc.setVisible(true);
        btnBuscaFunc.setEnabled(false);
    }//GEN-LAST:event_btnBuscaFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscaFunc;
    private javax.swing.JButton btnCancelaBusca;
    private javax.swing.JCheckBox cbBuscarCPF;
    private javax.swing.JCheckBox cbBuscarCTPS;
    private javax.swing.JCheckBox cbBuscarCidade;
    private javax.swing.JCheckBox cbBuscarNome;
    private javax.swing.JCheckBox cbExibirBairro;
    private javax.swing.JCheckBox cbExibirCEP;
    private javax.swing.JCheckBox cbExibirCPF;
    private javax.swing.JCheckBox cbExibirCTPS;
    private javax.swing.JCheckBox cbExibirCidade;
    private javax.swing.JCheckBox cbExibirNome;
    private javax.swing.JCheckBox cbExibirRua;
    private javax.swing.JCheckBox cbExibirSalario;
    private javax.swing.JCheckBox cbFiltrarSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField txtBuscaCPF;
    private javax.swing.JFormattedTextField txtBuscaCTPS;
    private javax.swing.JTextField txtBuscaCidade;
    private javax.swing.JTextField txtBuscaNome;
    private javax.swing.JFormattedTextField txtSalMax;
    private javax.swing.JFormattedTextField txtSalMin;
    // End of variables declaration//GEN-END:variables
}
