/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author d-den
 */
public class GerenciaComanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciaComanda
     */
    JanelaPrincipal jp;
    String cpf;
    Connection con;
    public GerenciaComanda(String c,JanelaPrincipal j) {
        initComponents();
        jp = j;
        cpf = c;
        String sql = "SELECT * FROM pessoaComanda WHERE cpf_cliente = " + cpf;
        try {
            con = ConnectionFactory.createConnection();
            PreparedStatement stm = con.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            while(rs.next()){
                txtCPFCli.setText(""+rs.getString("cpf_cliente"));
                txtCPFFunc.setText(""+rs.getString("cpf_funcionario"));
                txtVal.setText(""+rs.getString("valor").replace('.', ','));
                Vector<String> nome_jogos = new Vector<String>();
                nome_jogos.add("Nenhum");
                sql = "SELECT nome_jogo FROM jogo"
                        + " LEFT JOIN comanda on codigo_jogo = cod_jogo_alugado"
                        + " WHERE comanda.cod_jogo_alugado IS NULL and locacao=true";
                stm = con.prepareStatement(sql);
                ResultSet jogos = stm.executeQuery();
                while(jogos.next())
                    nome_jogos.add(jogos.getString("nome_jogo"));
                
                if(!(rs.getString("nome_jogo") == null)){
                    nome_jogos.add(rs.getString("nome_jogo"));
                    cbbJogoAlugado.setModel(new DefaultComboBoxModel(nome_jogos));
                    cbbJogoAlugado.setSelectedIndex(cbbJogoAlugado.getItemCount()-1);
                }else{
                    cbbJogoAlugado.setModel(new DefaultComboBoxModel(nome_jogos));
                    cbbJogoAlugado.setSelectedIndex(0);
                }
                    
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar cliente!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            return;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        try {
            ResultSet r1,r2;
            sql = "SELECT nome_item,quantidade,preco_item FROM itens_cardapio,comanda_consome_itens"
                + " WHERE codigo = codigo_item and cpf_cliente = "+cpf;
            PreparedStatement stm = con.prepareStatement(sql);
            r1 = stm.executeQuery();
            sql = "SELECT nome_jogo,quantidade,preco_jogo FROM jogo,comanda_compra_jogos"
                + " WHERE codigo = codigo_jogo and cpf_cliente = "+cpf;
            stm = con.prepareStatement(sql);
            r2 = stm.executeQuery();
            tblNota.setModel(buildTableModel(r1,r2));
            tblNota.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs, ResultSet r2) throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("Nome");
        columnNames.add("Quantidade");
        columnNames.add("Preço(un.)");
        int columnCount = 3;
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        while(r2.next()){
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(r2.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNota = new javax.swing.JTable();
        txtCPFFunc = new javax.swing.JTextField();
        txtCPFCli = new javax.swing.JTextField();
        cbbJogoAlugado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnAddJogo = new javax.swing.JButton();
        btnRemoveJogo = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        btnFechaComanda = new javax.swing.JButton();
        btnCancelaEditComanda = new javax.swing.JButton();
        btnEditComanda = new javax.swing.JButton();
        txtVal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar Comanda");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("CPF do Cliente:");

        jLabel2.setText("CPF do Funcionário:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Jogo Alugado:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Itens / Jogos Comprados"));

        tblNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Preço (un.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNota.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblNota);

        txtCPFFunc.setEditable(false);

        txtCPFCli.setEditable(false);

        cbbJogoAlugado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ações"));
        jPanel1.setToolTipText("");

        btnAddJogo.setText("Adicionar Jogo");
        btnAddJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogoActionPerformed(evt);
            }
        });

        btnRemoveJogo.setText("Remover Jogo");
        btnRemoveJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveJogoActionPerformed(evt);
            }
        });

        btnAddItem.setText("Adicionar Consumível");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setText("Remover Consumível");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        btnFechaComanda.setText("Fechar Comanda");
        btnFechaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveJogo)
                    .addComponent(btnAddJogo))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemoveItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btnFechaComanda))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJogo)
                    .addComponent(btnAddItem)
                    .addComponent(btnFechaComanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveJogo)
                    .addComponent(btnRemoveItem))
                .addContainerGap())
        );

        btnCancelaEditComanda.setText("Cancelar");
        btnCancelaEditComanda.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaEditComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaEditComandaActionPerformed(evt);
            }
        });

        btnEditComanda.setText("Salvar");
        btnEditComanda.setPreferredSize(new java.awt.Dimension(100, 23));
        btnEditComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditComandaActionPerformed(evt);
            }
        });

        txtVal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbbJogoAlugado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCPFFunc)
                                    .addComponent(txtCPFCli))
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtVal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelaEditComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(btnEditComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbJogoAlugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaEditComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setBounds(0, 0, 560, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaEditComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaEditComandaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaEditComandaActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        AddItemComanda addItem = new AddItemComanda(this,cpf);
        btnAddItem.setEnabled(false);
        jp.jDesktopPane1.add(addItem);
        Dimension d = jp.jDesktopPane1.getSize();
        addItem.setLocation((d.width - addItem.getSize().width) / 2, (d.height - addItem.getSize().height) / 2);
        addItem.setVisible(true);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:
        RemoveItemComanda removeItem = new RemoveItemComanda(this,cpf);
        btnRemoveItem.setEnabled(false);
        jp.jDesktopPane1.add(removeItem);
        Dimension d = jp.jDesktopPane1.getSize();
        removeItem.setLocation((d.width - removeItem.getSize().width) / 2, (d.height - removeItem.getSize().height) / 2);
        removeItem.setVisible(true);
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnAddJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogoActionPerformed
        // TODO add your handling code here:
        AddJogoComanda addJogo = new AddJogoComanda(this,cpf);
        btnAddJogo.setEnabled(false);
        jp.jDesktopPane1.add(addJogo);
        Dimension d = jp.jDesktopPane1.getSize();
        addJogo.setLocation((d.width - addJogo.getSize().width) / 2, (d.height - addJogo.getSize().height) / 2);
        addJogo.setVisible(true);
    }//GEN-LAST:event_btnAddJogoActionPerformed

    private void btnRemoveJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveJogoActionPerformed
        // TODO add your handling code here:
        RemoveJogoComanda removeJogo = new RemoveJogoComanda(this,cpf);
        btnRemoveJogo.setEnabled(false);
        jp.jDesktopPane1.add(removeJogo);
        Dimension d = jp.jDesktopPane1.getSize();
        removeJogo.setLocation((d.width - removeJogo.getSize().width) / 2, (d.height - removeJogo.getSize().height) / 2);
        removeJogo.setVisible(true);
    }//GEN-LAST:event_btnRemoveJogoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciaComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnEditComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditComandaActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT codigo_jogo FROM jogo WHERE nome_jogo = '"+cbbJogoAlugado.getSelectedItem()+"'";
        ResultSet r1;
        
        try {
            PreparedStatement stm = con.prepareStatement(sql);
            r1 = stm.executeQuery();

            int rowcount = 0;
            if (r1.last()) {
              rowcount = r1.getRow();
              r1.beforeFirst(); // not rs.first() because the rs.next() below will move on, missing the first element
            }
            if(rowcount==0){
                sql = "UPDATE comanda SET cod_jogo_alugado = null WHERE cpf_cliente = "+cpf;
            }else{
                while(r1.next()){
                    sql = "UPDATE comanda SET cod_jogo_alugado = " + r1.getString("codigo_jogo") + " WHERE cpf_cliente = " + cpf;
                }
            }
            stm = con.prepareStatement(sql);
            stm.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a atualização!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        JOptionPane.showMessageDialog(null, "Comanda atualizado com sucesso!","Atualização",JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnEditComandaActionPerformed

    private void btnFechaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaComandaActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(jp, "Tem certeza que deseja fechar a comanda?", "Atenção!", JOptionPane.OK_CANCEL_OPTION);
        if(op == JOptionPane.CANCEL_OPTION)
            return;
        String val = txtVal.getText();
        String sql;
        PreparedStatement stm;
        try {
            sql = "DELETE FROM comanda_consome_itens WHERE cpf_cliente = "+cpf;
            stm = con.prepareStatement(sql);
            stm.executeUpdate();
            sql = "DELETE FROM comanda_compra_jogos WHERE cpf_cliente = "+cpf;
            stm = con.prepareStatement(sql);
            stm.executeUpdate();
            sql = "DELETE FROM comanda WHERE cpf_cliente = " + cpf;
            stm = con.prepareStatement(sql);
            stm.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(jp, "Não foi possível fechar a comanda!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            //dispose();
            return;
        }
        JOptionPane.showMessageDialog(jp,"Comanda fechada!\nTotal a pagar: R$ "+val, "Pagamento",JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnFechaComandaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddItem;
    public javax.swing.JButton btnAddJogo;
    private javax.swing.JButton btnCancelaEditComanda;
    private javax.swing.JButton btnEditComanda;
    private javax.swing.JButton btnFechaComanda;
    public javax.swing.JButton btnRemoveItem;
    public javax.swing.JButton btnRemoveJogo;
    private javax.swing.JComboBox<String> cbbJogoAlugado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNota;
    private javax.swing.JTextField txtCPFCli;
    private javax.swing.JTextField txtCPFFunc;
    private javax.swing.JTextField txtVal;
    // End of variables declaration//GEN-END:variables
}
