/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    //public static boolean aberto = false;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadFunc = new javax.swing.JMenuItem();
        menuCadCli = new javax.swing.JMenuItem();
        menuCadItem = new javax.swing.JMenuItem();
        menuCadJogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadComanda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBuscaComanda = new javax.swing.JMenuItem();
        menuBuscaCli = new javax.swing.JMenuItem();
        menuBuscaFunc = new javax.swing.JMenuItem();
        menuBuscaItem = new javax.swing.JMenuItem();
        menuBuscaJogo = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuFecharProg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho BD I");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        menuCadFunc.setText("Funcionário");
        menuCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadFunc);

        menuCadCli.setText("Cliente");
        menuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCliActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadCli);

        menuCadItem.setText("Consumível");
        menuCadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadItem);

        menuCadJogo.setText("Jogo");
        menuCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadJogoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadJogo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Criar");

        menuCadComanda.setText("Comanda");
        menuCadComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadComandaActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadComanda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pesquisar");

        menuBuscaComanda.setText("Comanda");
        menuBuscaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaComandaActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscaComanda);

        menuBuscaCli.setText("Cliente");
        menuBuscaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaCliActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscaCli);

        menuBuscaFunc.setText("Funcionário");
        menuBuscaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaFuncActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscaFunc);

        menuBuscaItem.setText("Consumível");
        menuBuscaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaItemActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscaItem);

        menuBuscaJogo.setText("Jogo");
        menuBuscaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaJogoActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscaJogo);

        jMenuBar1.add(jMenu3);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });

        menuFecharProg.setText("Fechar programa");
        menuFecharProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharProgActionPerformed(evt);
            }
        });
        menuSair.add(menuFecharProg);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBuscaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaCliActionPerformed
        // TODO add your handling code here:
        menuBuscaCli.setEnabled(false);
        BuscaCliente buscaCli = new BuscaCliente(this);
        jDesktopPane1.add(buscaCli);
        Dimension d = jDesktopPane1.getSize();
        buscaCli.setLocation((d.width - buscaCli.getSize().width) / 2, (d.height - buscaCli.getSize().height) / 2);
        buscaCli.setVisible(true);
    }//GEN-LAST:event_menuBuscaCliActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
       
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuFecharProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharProgActionPerformed
       int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Sair",JOptionPane.OK_CANCEL_OPTION);
       if(op == JOptionPane.YES_OPTION)
           System.exit(0);
    }//GEN-LAST:event_menuFecharProgActionPerformed

    private void menuCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncActionPerformed
        menuCadFunc.setEnabled(false);
        CadFuncionario cadFunc = new CadFuncionario(this);
        jDesktopPane1.add(cadFunc);
        Dimension d = jDesktopPane1.getSize();
        cadFunc.setLocation((d.width - cadFunc.getSize().width) / 2, (d.height - cadFunc.getSize().height) / 2);
        cadFunc.setVisible(true);
    }//GEN-LAST:event_menuCadFuncActionPerformed

    private void menuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCliActionPerformed
        // TODO add your handling code here:
        menuCadCli.setEnabled(false);
        CadCliente cadCli = new CadCliente(this);
        jDesktopPane1.add(cadCli);
        Dimension d = jDesktopPane1.getSize();
        cadCli.setLocation((d.width - cadCli.getSize().width) / 2, (d.height - cadCli.getSize().height) / 2);
        cadCli.setVisible(true);
    }//GEN-LAST:event_menuCadCliActionPerformed

    private void menuCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadJogoActionPerformed
        // TODO add your handling code here:
        menuCadJogo.setEnabled(false);
        CadJogo cadJogo = new CadJogo(this);
        jDesktopPane1.add(cadJogo);
        Dimension d = jDesktopPane1.getSize();
        cadJogo.setLocation((d.width - cadJogo.getSize().width) / 2, (d.height - cadJogo.getSize().height) / 2);
        cadJogo.setVisible(true);
    }//GEN-LAST:event_menuCadJogoActionPerformed

    private void menuCadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadItemActionPerformed
        menuCadItem.setEnabled(false);
        CadItem cadItem = new CadItem(this);
        jDesktopPane1.add(cadItem);
        Dimension d = jDesktopPane1.getSize();
        cadItem.setLocation((d.width - cadItem.getSize().width) / 2, (d.height - cadItem.getSize().height) / 2);
        cadItem.setVisible(true);
    }//GEN-LAST:event_menuCadItemActionPerformed

    private void menuCadComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadComandaActionPerformed
        // TODO add your handling code here:
        menuCadComanda.setEnabled(false);
        CadComanda cadComanda = new CadComanda(this);
        jDesktopPane1.add(cadComanda);
        Dimension d = jDesktopPane1.getSize();
        cadComanda.setLocation((d.width - cadComanda.getSize().width) / 2, (d.height - cadComanda.getSize().height) / 2);
        cadComanda.setVisible(true);
    }//GEN-LAST:event_menuCadComandaActionPerformed

    private void menuBuscaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaFuncActionPerformed
        // TODO add your handling code here:
        menuBuscaFunc.setEnabled(false);
        BuscaFuncionario buscaFunc = new BuscaFuncionario(this);
        jDesktopPane1.add(buscaFunc);
        Dimension d = jDesktopPane1.getSize();
        buscaFunc.setLocation((d.width - buscaFunc.getSize().width) / 2, (d.height - buscaFunc.getSize().height) / 2);
        buscaFunc.setVisible(true);
    }//GEN-LAST:event_menuBuscaFuncActionPerformed

    private void menuBuscaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaJogoActionPerformed
        // TODO add your handling code here:
        menuBuscaJogo.setEnabled(false);
        BuscaJogo buscaJogo = new BuscaJogo(this);
        jDesktopPane1.add(buscaJogo);
        Dimension d = jDesktopPane1.getSize();
        buscaJogo.setLocation((d.width - buscaJogo.getSize().width) / 2, (d.height - buscaJogo.getSize().height) / 2);
        buscaJogo.setVisible(true);
    }//GEN-LAST:event_menuBuscaJogoActionPerformed

    private void menuBuscaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaItemActionPerformed
        // TODO add your handling code here:
        menuBuscaItem.setEnabled(false);
        BuscaItem buscaItem = new BuscaItem(this);
        jDesktopPane1.add(buscaItem);
        Dimension d = jDesktopPane1.getSize();
        buscaItem.setLocation((d.width - buscaItem.getSize().width) / 2, (d.height - buscaItem.getSize().height) / 2);
        buscaItem.setVisible(true);
    }//GEN-LAST:event_menuBuscaItemActionPerformed

    private void menuBuscaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaComandaActionPerformed
        // TODO add your handling code here:
        menuBuscaComanda.setEnabled(false);
        BuscaComanda buscaComanda = new BuscaComanda(this);
        jDesktopPane1.add(buscaComanda);
        Dimension d = jDesktopPane1.getSize();
        buscaComanda.setLocation((d.width - buscaComanda.getSize().width) / 2, (d.height - buscaComanda.getSize().height) / 2);
        buscaComanda.setVisible(true);
    }//GEN-LAST:event_menuBuscaComandaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem menuBuscaCli;
    public javax.swing.JMenuItem menuBuscaComanda;
    public javax.swing.JMenuItem menuBuscaFunc;
    public javax.swing.JMenuItem menuBuscaItem;
    public javax.swing.JMenuItem menuBuscaJogo;
    public javax.swing.JMenuItem menuCadCli;
    public javax.swing.JMenuItem menuCadComanda;
    public javax.swing.JMenuItem menuCadFunc;
    public javax.swing.JMenuItem menuCadItem;
    public javax.swing.JMenuItem menuCadJogo;
    private javax.swing.JMenuItem menuFecharProg;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
