/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author d-den
 */
public class RemoveItemComanda extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoveItem
     */
    GerenciaComanda fonte;
    String cpf;
    Connection con;
    public RemoveItemComanda(GerenciaComanda f, String cpf) {
        initComponents();
        fonte = f;
        this.cpf = cpf;
        try {
            con = ConnectionFactory.createConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodItem = new javax.swing.JTextField();
        btnCancelaRemoveItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();

        setClosable(true);
        setTitle("Remover Item");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Código do Item:");

        btnCancelaRemoveItem.setText("Cancelar");
        btnCancelaRemoveItem.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelaRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaRemoveItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setText("Remover");
        btnRemoveItem.setPreferredSize(new java.awt.Dimension(100, 23));
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodItem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelaRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelaRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setBounds(0, 0, 360, 125);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelaRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaRemoveItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelaRemoveItemActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(RemoveItemComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        fonte.btnRemoveItem.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM comanda_consome_itens WHERE cpf_cliente = "+cpf+" AND codigo = "+txtCodItem.getText();
        try {
            PreparedStatement stm = con.prepareStatement(sql);
            stm.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(fonte.jp, "Não foi possível realizar remover o item!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(fonte.jp, "Item removido com sucesso!","Remoção",JOptionPane.INFORMATION_MESSAGE);
        txtCodItem.setText("");
        
        GerenciaComanda gerenciaComanda = new GerenciaComanda(cpf,fonte.jp);
        fonte.jp.jDesktopPane1.add(gerenciaComanda);
        Dimension d = fonte.jp.jDesktopPane1.getSize();
        gerenciaComanda.setLocation((d.width - gerenciaComanda.getSize().width) / 2, (d.height - gerenciaComanda.getSize().height) / 2);
        gerenciaComanda.setVisible(true);
        fonte.dispose();
        this.moveToFront();
        try {
            this.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AddItemComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        fonte = gerenciaComanda;
    }//GEN-LAST:event_btnRemoveItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelaRemoveItem;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCodItem;
    // End of variables declaration//GEN-END:variables
}
