/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

/**
 *
 * @author d-den
 */
public class ResultadoBuscaCli extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadoBuscaCli
     */
    BuscaCliente fonte;
    public ResultadoBuscaCli(BuscaCliente f) {
        initComponents();
        fonte = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEditCli = new javax.swing.JMenuItem();
        menuExcluiCli = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResBuscaCli = new javax.swing.JTable();

        menuEditCli.setText("Editar");
        menuEditCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditCliActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEditCli);

        menuExcluiCli.setText("Excluir");
        jPopupMenu1.add(menuExcluiCli);

        setClosable(true);
        setResizable(true);
        setTitle("Resultado da Busca");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tbResBuscaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbResBuscaCli.getTableHeader().setReorderingAllowed(false);
        tbResBuscaCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbResBuscaCliMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbResBuscaCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        setBounds(0, 0, 650, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        fonte.btnBuscaCli.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void tbResBuscaCliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResBuscaCliMouseReleased
        // TODO add your handling code here:
        int r = tbResBuscaCli.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tbResBuscaCli.getRowCount()) {
            tbResBuscaCli.setRowSelectionInterval(r, r);
        } else {
            tbResBuscaCli.clearSelection();
        }
        int rowindex = tbResBuscaCli.getSelectedRow();
        if (rowindex < 0)
            return;
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {
            JPopupMenu popup = jPopupMenu1;
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbResBuscaCliMouseReleased

    private void menuEditCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditCliActionPerformed
        // TODO add your handling code here:
        EditCliente editCliente = new EditCliente();
        fonte.jp.jDesktopPane1.add(editCliente);
        Dimension d = fonte.jp.jDesktopPane1.getSize();
        editCliente.setLocation((d.width - editCliente.getSize().width) / 2, (d.height - editCliente.getSize().height) / 2);
        editCliente.setVisible(true);
    }//GEN-LAST:event_menuEditCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuEditCli;
    private javax.swing.JMenuItem menuExcluiCli;
    private javax.swing.JTable tbResBuscaCli;
    // End of variables declaration//GEN-END:variables
}
