/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author d-den
 */
public class ResultadoBuscaItem extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadoBuscaItem
     */
    BuscaItem fonte;
    ResultSet rs;
    Connection con;
    public ResultadoBuscaItem(BuscaItem f, ResultSet r) {
        initComponents();
        fonte = f;
        rs = r;
        try {
            con = ConnectionFactory.createConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            tbResBuscaItem.setModel(buildTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEditaItem = new javax.swing.JMenuItem();
        menuExcluiItem = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResBuscaItem = new javax.swing.JTable();

        menuEditaItem.setText("Editar");
        menuEditaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditaItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEditaItem);

        menuExcluiItem.setText("Excluir");
        menuExcluiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluiItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuExcluiItem);

        setClosable(true);
        setResizable(true);
        setTitle("Resultado da Busca");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tbResBuscaItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbResBuscaItem.getTableHeader().setReorderingAllowed(false);
        tbResBuscaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbResBuscaItemMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbResBuscaItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        setBounds(0, 0, 650, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void tbResBuscaItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResBuscaItemMouseReleased
        // TODO add your handling code here:
        int r = tbResBuscaItem.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tbResBuscaItem.getRowCount()) {
            tbResBuscaItem.setRowSelectionInterval(r, r);
        } else {
            tbResBuscaItem.clearSelection();
        }
        int rowindex = tbResBuscaItem.getSelectedRow();
        if (rowindex < 0)
            return;
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {
            JPopupMenu popup = jPopupMenu1;
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbResBuscaItemMouseReleased

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column).toUpperCase());
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }
    
    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ResultadoBuscaItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        fonte.btnBuscaItem.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void menuEditaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditaItemActionPerformed
        // TODO add your handling code here:
        
        
        EditItem editItem = new EditItem(tbResBuscaItem.getValueAt(tbResBuscaItem.getSelectedRow(), 0).toString(),this);
        fonte.jp.jDesktopPane1.add(editItem);
        Dimension d = fonte.jp.jDesktopPane1.getSize();
        editItem.setLocation((d.width - editItem.getSize().width) / 2, (d.height - editItem.getSize().height) / 2);
        editItem.setVisible(true);
    }//GEN-LAST:event_menuEditaItemActionPerformed

    private void menuExcluiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluiItemActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(fonte.jp, "Tem certeza que deseja excluir jogo?", "Atenção!", JOptionPane.OK_CANCEL_OPTION);
        if(op == JOptionPane.CANCEL_OPTION)
            return;
        String sql = "DELETE FROM itens_cardapio WHERE codigo_item = " + tbResBuscaItem.getValueAt(tbResBuscaItem.getSelectedRow(), 0);
        try {
            PreparedStatement stm = con.prepareStatement(sql);
            stm.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(fonte.jp, "Não foi possível exluir item!\n"+ex.toString(),"Erro",JOptionPane.ERROR_MESSAGE);
            //dispose();
            return;
        }
        JOptionPane.showMessageDialog(fonte.jp,"Item excluído com sucesso!", "Exclusão",JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_menuExcluiItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuEditaItem;
    private javax.swing.JMenuItem menuExcluiItem;
    private javax.swing.JTable tbResBuscaItem;
    // End of variables declaration//GEN-END:variables
}
