/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unespbcc.trabalhobd1;

import java.awt.Dimension;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

/**
 *
 * @author d-den
 */
public class ResultadoBuscaJogo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadoBuscaJogo
     */
    BuscaJogo fonte;
    public ResultadoBuscaJogo(BuscaJogo f) {
        initComponents();
        fonte = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEditaJogo = new javax.swing.JMenuItem();
        menuExcluiJogo = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResBuscaJogo = new javax.swing.JTable();

        menuEditaJogo.setText("Editar");
        menuEditaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditaJogoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEditaJogo);

        menuExcluiJogo.setText("Excluir");
        jPopupMenu1.add(menuExcluiJogo);

        setClosable(true);
        setResizable(true);
        setTitle("Resultado da Busca");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tbResBuscaJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbResBuscaJogo.getTableHeader().setReorderingAllowed(false);
        tbResBuscaJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbResBuscaJogoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbResBuscaJogo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        setBounds(0, 0, 630, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        fonte.btnBuscaJogo.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void tbResBuscaJogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbResBuscaJogoMouseReleased
        // TODO add your handling code here:
        int r = tbResBuscaJogo.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tbResBuscaJogo.getRowCount()) {
            tbResBuscaJogo.setRowSelectionInterval(r, r);
        } else {
            tbResBuscaJogo.clearSelection();
        }
        int rowindex = tbResBuscaJogo.getSelectedRow();
        if (rowindex < 0)
            return;
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {
            JPopupMenu popup = jPopupMenu1;
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbResBuscaJogoMouseReleased

    private void menuEditaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditaJogoActionPerformed
        // TODO add your handling code here:
        EditJogo editJogo = new EditJogo();
        fonte.jp.jDesktopPane1.add(editJogo);
        Dimension d = fonte.jp.jDesktopPane1.getSize();
        editJogo.setLocation((d.width - editJogo.getSize().width) / 2, (d.height - editJogo.getSize().height) / 2);
        editJogo.setVisible(true);
    }//GEN-LAST:event_menuEditaJogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuEditaJogo;
    private javax.swing.JMenuItem menuExcluiJogo;
    private javax.swing.JTable tbResBuscaJogo;
    // End of variables declaration//GEN-END:variables
}
